"""
QuickBooks Online ERP Integration

All QuickBooks-specific API calls: journal entries, bills, vendors, credits,
settlements, attachments, and token refresh.
"""
from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

import httpx

from clearledgr.integrations.erp_sanitization import (
    _build_quickbooks_vendor_credit_lookup_query,
    _build_quickbooks_vendor_lookup_query,
    _escape_query_literal,
    _sanitize_quickbooks_like_operand,
)

logger = logging.getLogger(__name__)

_ERP_TIMEOUT = 30


def _quickbooks_headers(connection) -> Dict[str, str]:
    return {
        "Authorization": f"Bearer {connection.access_token}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }


def _extract_quickbooks_fault_message(payload: Optional[Dict[str, Any]]) -> Optional[str]:
    if not isinstance(payload, dict):
        return None
    fault = payload.get("Fault")
    if isinstance(fault, dict):
        errors = fault.get("Error")
        if isinstance(errors, list):
            for error in errors:
                if not isinstance(error, dict):
                    continue
                for key in ("Detail", "Message", "code"):
                    detail = str(error.get(key) or "").strip()
                    if detail:
                        return detail
    for key in ("fault", "error", "message"):
        detail = str(payload.get(key) or "").strip()
        if detail:
            return detail
    return None


# ==================== Journal Entry ====================

async def post_to_quickbooks(
    connection,
    entry: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Post journal entry to QuickBooks Online.

    Uses QuickBooks API:
    https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/journalentry
    """
    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not properly configured"}

    # Build QuickBooks journal entry format
    qb_entry = {
        "TxnDate": entry.get("date", datetime.now().strftime("%Y-%m-%d")),
        "PrivateNote": entry.get("description", "Auto-generated by Clearledgr"),
        "Line": [],
    }

    for line in entry.get("lines", []):
        qb_line = {
            "DetailType": "JournalEntryLineDetail",
            "Amount": line.get("debit", 0) or line.get("credit", 0),
            "JournalEntryLineDetail": {
                "PostingType": "Debit" if line.get("debit", 0) > 0 else "Credit",
                "AccountRef": {
                    "value": line.get("account", "1"),
                    "name": line.get("account_name", "Unknown"),
                },
            },
        }
        qb_entry["Line"].append(qb_line)

    # Make API call
    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/journalentry"

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.post(
                url,
                json=qb_entry,
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "Content-Type": "application/json",
                    "Accept": "application/json",
                },
                timeout=30,
            )

            if response.status_code == 401:
                # Token expired - would need to refresh
                logger.warning("QuickBooks token expired, needs refresh")
                return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}

            response.raise_for_status()
            result = response.json()

            logger.info(f"Posted to QuickBooks: {result.get('JournalEntry', {}).get('Id')}")
            return {
                "status": "success",
                "erp": "quickbooks",
                "entry_id": result.get("JournalEntry", {}).get("Id"),
                "sync_token": result.get("JournalEntry", {}).get("SyncToken"),
            }

    except httpx.HTTPStatusError as e:
        logger.error("QuickBooks API error: %s", e.response.status_code)
        return {"status": "error", "erp": "quickbooks", "reason": f"QuickBooks API {e.response.status_code}"}
    except Exception as e:
        logger.error("QuickBooks error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "posting_failed"}


# ==================== Token Refresh ====================

async def refresh_quickbooks_token(connection) -> Optional[str]:
    """Refresh QuickBooks OAuth token."""
    if not connection.refresh_token or not connection.client_id or not connection.client_secret:
        return None

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.post(
                "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
                data={
                    "grant_type": "refresh_token",
                    "refresh_token": connection.refresh_token,
                },
                auth=(connection.client_id, connection.client_secret),
            )
            response.raise_for_status()
            tokens = response.json()

            connection.access_token = tokens.get("access_token")
            connection.refresh_token = tokens.get("refresh_token")

            return connection.access_token
    except Exception as e:
        logger.error("Failed to refresh QuickBooks token: %s", type(e).__name__)
        return None


# ==================== Bill Posting ====================

async def post_bill_to_quickbooks(
    connection,
    bill,
    gl_map: Optional[Dict[str, str]] = None,
) -> Dict[str, Any]:
    """
    Post vendor bill to QuickBooks Online.

    API: https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/bill
    """
    from clearledgr.integrations.erp_router import get_account_code

    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not properly configured"}

    expense_account = get_account_code("quickbooks", "expenses", gl_map)

    # Build QuickBooks Bill format
    qb_bill = {
        "VendorRef": {"value": bill.vendor_id, "name": bill.vendor_name},
        "TxnDate": bill.invoice_date or datetime.now().strftime("%Y-%m-%d"),
        "DueDate": bill.due_date,
        "DocNumber": bill.invoice_number,
        "PrivateNote": bill.description or f"Invoice from {bill.vendor_name}",
        "Line": [],
    }

    # Add line items or create single expense line
    if bill.line_items:
        for i, item in enumerate(bill.line_items):
            qb_bill["Line"].append({
                "Id": str(i + 1),
                "DetailType": "AccountBasedExpenseLineDetail",
                "Amount": item.get("amount", 0),
                "Description": item.get("description", ""),
                "AccountBasedExpenseLineDetail": {
                    "AccountRef": {"value": item.get("account_id", expense_account)},
                }
            })
    else:
        # Single line item for full amount
        qb_bill["Line"].append({
            "Id": "1",
            "DetailType": "AccountBasedExpenseLineDetail",
            "Amount": bill.amount,
            "Description": bill.description or f"Invoice {bill.invoice_number}",
            "AccountBasedExpenseLineDetail": {
                "AccountRef": {"value": expense_account},
            }
        })

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/bill"

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.post(
                url,
                json=qb_bill,
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "Content-Type": "application/json",
                    "Accept": "application/json",
                },
                timeout=30,
            )

            if response.status_code == 401:
                return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}

            response.raise_for_status()
            result = response.json()

            bill_data = result.get("Bill", {})
            logger.info("Posted Bill to QuickBooks: %s", bill_data.get("Id"))
            return {
                "status": "success",
                "erp": "quickbooks",
                "bill_id": bill_data.get("Id"),
                "doc_number": bill_data.get("DocNumber"),
                "sync_token": bill_data.get("SyncToken"),
            }

    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("QuickBooks Bill API HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        if status_code == 404:
            reason = "erp_realm_id_invalid"
            logger.error(
                "QuickBooks 404 — likely realm_id mismatch (realm_id=%s). "
                "Verify the company is accessible with current credentials.",
                connection.realm_id,
            )
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("QuickBooks Bill error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "bill_posting_failed"}


# ==================== Bill Lookup ====================

async def get_bill_quickbooks(
    connection,
    bill_id: str,
) -> Dict[str, Any]:
    """Fetch a QuickBooks bill with enough context for follow-on actions."""
    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not properly configured"}

    safe_id = _sanitize_quickbooks_like_operand(bill_id)
    if not safe_id:
        return {"status": "error", "erp": "quickbooks", "reason": "invalid_bill_reference"}
    literal = _escape_query_literal(safe_id)
    query = (
        "SELECT Id, DocNumber, TotalAmt, Balance, VendorRef, APAccountRef "
        f"FROM Bill WHERE Id = '{literal}'"
    )
    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                params={"query": query},
                headers={"Authorization": f"Bearer {connection.access_token}"},
                timeout=30,
            )
            if response.status_code == 401:
                return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}

            response.raise_for_status()
            bills = response.json().get("QueryResponse", {}).get("Bill", [])
            if not bills:
                return {
                    "status": "error",
                    "erp": "quickbooks",
                    "reason": "bill_not_found",
                    "target_erp_reference": bill_id,
                }
            bill = bills[0]
            vendor_ref = bill.get("VendorRef") if isinstance(bill.get("VendorRef"), dict) else {}
            ap_account_ref = bill.get("APAccountRef") if isinstance(bill.get("APAccountRef"), dict) else {}
            return {
                "status": "success",
                "erp": "quickbooks",
                "bill_id": bill.get("Id"),
                "doc_number": bill.get("DocNumber"),
                "total_amt": bill.get("TotalAmt"),
                "balance": bill.get("Balance"),
                "vendor_id": vendor_ref.get("value"),
                "vendor_name": vendor_ref.get("name"),
                "ap_account_id": ap_account_ref.get("value"),
            }
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("QuickBooks bill GET HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        fault = _extract_quickbooks_fault_message(payload)
        if fault:
            reason = fault
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("QuickBooks bill GET error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "bill_lookup_failed"}


async def find_vendor_credit_quickbooks(
    connection,
    credit_note_number: str,
) -> Optional[Dict[str, Any]]:
    """Find a QuickBooks vendor credit by document number."""
    if not connection.access_token or not connection.realm_id:
        return None
    safe_number = _sanitize_quickbooks_like_operand(credit_note_number)
    query = _build_quickbooks_vendor_credit_lookup_query(credit_note_operand=safe_number)
    if not query:
        return None
    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                params={"query": query},
                headers={"Authorization": f"Bearer {connection.access_token}"},
                timeout=30,
            )
            response.raise_for_status()
            credits = response.json().get("QueryResponse", {}).get("VendorCredit", [])
            if credits:
                credit = credits[0]
                vendor_ref = credit.get("VendorRef") if isinstance(credit.get("VendorRef"), dict) else {}
                return {
                    "credit_note_id": credit.get("Id"),
                    "credit_note_number": credit.get("DocNumber"),
                    "remaining_credit": credit.get("Balance", credit.get("TotalAmt")),
                    "vendor_id": vendor_ref.get("value"),
                    "erp": "quickbooks",
                }
    except Exception as e:
        logger.error("QuickBooks vendor credit lookup error: %s", e)
    return None


# ==================== Credit Application ====================

async def apply_credit_note_to_quickbooks(
    connection,
    application,
    *,
    gl_map: Optional[Dict[str, str]] = None,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Create/apply a QuickBooks vendor credit against a posted bill."""
    from clearledgr.integrations.erp_router import get_account_code

    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not properly configured"}

    missing_fields = []
    target_ref = str(application.target_erp_reference or "").strip()
    if not target_ref:
        missing_fields.append("target_erp_reference")
    credit_note_number = str(application.credit_note_number or "").strip()
    if not credit_note_number:
        missing_fields.append("credit_note_number")
    if float(application.amount or 0.0) <= 0:
        missing_fields.append("amount")
    if missing_fields:
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "quickbooks_credit_application_validation_failed",
            "missing_fields": missing_fields,
        }

    # Late-bound through erp_router so test patches on erp_router.* propagate.
    from clearledgr.integrations import erp_router as _router
    bill = await _router.get_bill_quickbooks(connection, target_ref)
    if bill.get("status") != "success":
        return bill
    if not bill.get("vendor_id"):
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "bill_vendor_not_resolved",
            "target_erp_reference": target_ref,
        }
    if not bill.get("ap_account_id"):
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "bill_ap_account_not_resolved",
            "target_erp_reference": target_ref,
        }

    vendor_credit = await _router.find_vendor_credit_quickbooks(connection, credit_note_number)
    if vendor_credit and vendor_credit.get("vendor_id") and str(vendor_credit.get("vendor_id")) != str(bill["vendor_id"]):
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "credit_note_vendor_mismatch",
            "credit_note_number": credit_note_number,
        }

    try:
        remaining_credit = float(
            (vendor_credit or {}).get("remaining_credit")
            if (vendor_credit or {}).get("remaining_credit") is not None
            else application.amount
        )
        if vendor_credit and round(float(application.amount or 0.0), 2) > round(remaining_credit, 2):
            return {
                "status": "error",
                "erp": "quickbooks",
                "reason": "credit_amount_exceeds_remaining_credit",
                "credit_note_number": credit_note_number,
                "remaining_credit": round(remaining_credit, 2),
            }
    except (TypeError, ValueError):
        pass

    vendor_credit_id = str((vendor_credit or {}).get("credit_note_id") or "").strip()
    expense_account = get_account_code("quickbooks", "expenses", gl_map)
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            if not vendor_credit_id:
                credit_url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/vendorcredit"
                credit_payload = {
                    "VendorRef": {"value": bill["vendor_id"]},
                    "APAccountRef": {"value": bill["ap_account_id"]},
                    "TxnDate": datetime.now().strftime("%Y-%m-%d"),
                    "DocNumber": credit_note_number[:21],
                    "PrivateNote": str(
                        application.note or f"Vendor credit {credit_note_number} for bill {bill.get('doc_number') or target_ref}"
                    )[:4000],
                    "Line": [
                        {
                            "Amount": round(float(application.amount or 0.0), 2),
                            "DetailType": "AccountBasedExpenseLineDetail",
                            "AccountBasedExpenseLineDetail": {
                                "AccountRef": {"value": expense_account},
                            },
                        }
                    ],
                }
                credit_response = await client.post(
                    credit_url,
                    json=credit_payload,
                    headers=_quickbooks_headers(connection),
                    timeout=30,
                )
                if credit_response.status_code == 401:
                    return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}
                credit_response.raise_for_status()
                credit_result = credit_response.json().get("VendorCredit", {})
                vendor_credit_id = str(credit_result.get("Id") or "").strip()
                if not vendor_credit_id:
                    return {"status": "error", "erp": "quickbooks", "reason": "no_vendor_credit_returned"}

            payment_url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/billpayment"
            payment_payload = {
                "VendorRef": {"value": bill["vendor_id"]},
                "TotalAmt": round(float(application.amount or 0.0), 2),
                "Line": [
                    {
                        "Amount": round(float(application.amount or 0.0), 2),
                        "LinkedTxn": [
                            {"TxnId": target_ref, "TxnType": "Bill"},
                            {"TxnId": vendor_credit_id, "TxnType": "VendorCredit"},
                        ],
                    }
                ],
            }
            payment_response = await client.post(
                payment_url,
                json=payment_payload,
                headers=_quickbooks_headers(connection),
                timeout=30,
            )
            if payment_response.status_code == 401:
                return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}
            payment_response.raise_for_status()
            bill_payment = payment_response.json().get("BillPayment", {})
            payment_id = bill_payment.get("Id")
            if not payment_id:
                return {"status": "error", "erp": "quickbooks", "reason": "no_bill_payment_returned"}
            return {
                "status": "success",
                "erp": "quickbooks",
                "erp_reference": payment_id,
                "payment_id": payment_id,
                "target_erp_reference": target_ref,
                "credit_note_reference": vendor_credit_id,
                "credit_note_number": credit_note_number,
                "amount": round(float(application.amount or 0.0), 2),
                "idempotency_key": idempotency_key,
            }
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("QuickBooks credit application HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        fault = _extract_quickbooks_fault_message(payload)
        if fault:
            reason = fault
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("QuickBooks credit application error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "credit_application_failed"}


# ==================== Settlement ====================

async def apply_settlement_to_quickbooks(
    connection,
    application,
    *,
    gl_map: Optional[Dict[str, str]] = None,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Create a QuickBooks bill payment against a posted bill."""
    from clearledgr.integrations.erp_router import get_account_code

    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not properly configured"}

    source_document_type = str(application.source_document_type or "").strip().lower()
    if source_document_type == "refund":
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "refund_settlement_api_not_available_for_connector",
        }

    missing_fields = []
    target_ref = str(application.target_erp_reference or "").strip()
    if not target_ref:
        missing_fields.append("target_erp_reference")
    if float(application.amount or 0.0) <= 0:
        missing_fields.append("amount")
    if missing_fields:
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "quickbooks_settlement_validation_failed",
            "missing_fields": missing_fields,
        }

    # Late-bound through erp_router so test patches on erp_router.* propagate.
    from clearledgr.integrations import erp_router as _router
    bill = await _router.get_bill_quickbooks(connection, target_ref)
    if bill.get("status") != "success":
        return bill
    if not bill.get("vendor_id"):
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": "bill_vendor_not_resolved",
            "target_erp_reference": target_ref,
        }

    payment_payload = {
        "VendorRef": {"value": bill["vendor_id"]},
        "PayType": "Check",
        "CheckPayment": {
            "BankAccountRef": {"value": get_account_code("quickbooks", "cash", gl_map)},
        },
        "TotalAmt": round(float(application.amount or 0.0), 2),
        "Line": [
            {
                "Amount": round(float(application.amount or 0.0), 2),
                "LinkedTxn": [{"TxnId": target_ref, "TxnType": "Bill"}],
            }
        ],
    }
    if application.source_reference:
        payment_payload["PrivateNote"] = str(application.source_reference)[:4000]

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/billpayment"
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.post(
                url,
                json=payment_payload,
                headers=_quickbooks_headers(connection),
                timeout=30,
            )
            if response.status_code == 401:
                return {"status": "error", "erp": "quickbooks", "reason": "Token expired", "needs_reauth": True}

            response.raise_for_status()
            bill_payment = response.json().get("BillPayment", {})
            payment_id = bill_payment.get("Id")
            if not payment_id:
                return {"status": "error", "erp": "quickbooks", "reason": "no_bill_payment_returned"}
            return {
                "status": "success",
                "erp": "quickbooks",
                "erp_reference": payment_id,
                "payment_id": payment_id,
                "target_erp_reference": target_ref,
                "amount": round(float(application.amount or 0.0), 2),
                "source_reference": application.source_reference,
                "idempotency_key": idempotency_key,
            }
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("QuickBooks settlement payment HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        fault = _extract_quickbooks_fault_message(payload)
        if fault:
            reason = fault
        return {
            "status": "error",
            "erp": "quickbooks",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("QuickBooks settlement payment error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "settlement_application_failed"}


# ==================== Vendor Management ====================

async def create_vendor_quickbooks(
    connection,
    vendor,
) -> Dict[str, Any]:
    """Create vendor in QuickBooks."""
    if not connection.access_token or not connection.realm_id:
        return {"status": "error", "erp": "quickbooks", "reason": "QuickBooks not configured"}

    qb_vendor = {
        "DisplayName": vendor.name,
        "PrintOnCheckName": vendor.name,
    }

    if vendor.email:
        qb_vendor["PrimaryEmailAddr"] = {"Address": vendor.email}
    if vendor.phone:
        qb_vendor["PrimaryPhone"] = {"FreeFormNumber": vendor.phone}
    if vendor.tax_id:
        qb_vendor["TaxIdentifier"] = vendor.tax_id

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/vendor"

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.post(
                url,
                json=qb_vendor,
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "Content-Type": "application/json",
                },
                timeout=30,
            )
            response.raise_for_status()
            result = response.json()

            vendor_data = result.get("Vendor", {})
            return {
                "status": "success",
                "vendor_id": vendor_data.get("Id"),
                "display_name": vendor_data.get("DisplayName"),
            }
    except Exception as e:
        logger.error("QuickBooks vendor creation error: %s", type(e).__name__)
        return {"status": "error", "erp": "quickbooks", "reason": "vendor_creation_failed"}


async def find_vendor_quickbooks(
    connection,
    name: Optional[str] = None,
    email: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Find vendor in QuickBooks by name or email."""
    if not connection.access_token or not connection.realm_id:
        return None

    # Build query via canonical helper with strict operand sanitization.
    name_operand = _sanitize_quickbooks_like_operand(name)
    email_operand = _sanitize_quickbooks_like_operand(email)
    query = _build_quickbooks_vendor_lookup_query(
        name_operand=name_operand,
        email_operand=email_operand,
    )
    if not query:
        return None

    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                params={"query": query},
                headers={"Authorization": f"Bearer {connection.access_token}"},
                timeout=30,
            )
            response.raise_for_status()
            result = response.json()

            vendors = result.get("QueryResponse", {}).get("Vendor", [])
            if vendors:
                v = vendors[0]
                return {
                    "vendor_id": v.get("Id"),
                    "name": v.get("DisplayName"),
                    "email": v.get("PrimaryEmailAddr", {}).get("Address"),
                }
    except Exception as e:
        logger.error(f"QuickBooks vendor search error: {e}")

    return None


# ==================== Bill Finder ====================

async def find_bill_quickbooks(
    connection,
    invoice_number: str,
) -> Optional[Dict[str, Any]]:
    """Check if a bill with this invoice number already exists in QuickBooks."""
    if not connection.access_token or not connection.realm_id:
        return None
    safe_number = _sanitize_quickbooks_like_operand(invoice_number)
    if not safe_number:
        return None
    literal = _escape_query_literal(safe_number)
    query = f"SELECT Id, DocNumber, TotalAmt FROM Bill WHERE DocNumber = '{literal}'"
    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                params={"query": query},
                headers={"Authorization": f"Bearer {connection.access_token}"},
                timeout=30,
            )
            response.raise_for_status()
            bills = response.json().get("QueryResponse", {}).get("Bill", [])
            if bills:
                b = bills[0]
                return {
                    "bill_id": b.get("Id"),
                    "doc_number": b.get("DocNumber"),
                    "amount": b.get("TotalAmt"),
                    "erp": "quickbooks",
                }
    except Exception as e:
        logger.error("QuickBooks bill lookup error: %s", e)
    return None


# ==================== Attachment ====================

async def _attach_to_quickbooks(
    connection, bill_id: str, file_bytes: bytes, filename: str,
) -> Optional[Dict[str, Any]]:
    """Upload attachment to a QuickBooks Bill via the Attachable API."""
    import io
    import json

    creds = connection.credentials or {}
    access_token = creds.get("access_token", "")
    realm_id = creds.get("realm_id", "")
    base_url = creds.get("base_url", "https://quickbooks.api.intuit.com")
    if not access_token or not realm_id:
        return None
    url = f"{base_url}/v3/company/{realm_id}/upload?minorversion=73"
    headers = {"Authorization": f"Bearer {access_token}", "Accept": "application/json"}
    files = {"file_content_01": (filename, io.BytesIO(file_bytes), "application/pdf")}
    metadata = json.dumps({
        "AttachableRef": [{"EntityRef": {"type": "Bill", "value": bill_id}}],
        "FileName": filename,
        "ContentType": "application/pdf",
    })
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(url, headers=headers, files=files, data={"file_metadata_01": metadata})
        resp.raise_for_status()
    return {"attached": True, "erp": "quickbooks"}


# ==================== Payment Status Lookup ====================

async def get_payment_status_quickbooks(
    connection,
    bill_id: str,
) -> Dict[str, Any]:
    """Read payment status for a QuickBooks bill. GET only — never executes payments.

    Checks the Bill's Balance field: Balance == 0 means fully paid.
    If Balance < TotalAmt but > 0, it's a partial payment.
    """
    if not connection.access_token or not connection.realm_id:
        return {"paid": False, "error": "QuickBooks not properly configured"}

    safe_id = _sanitize_quickbooks_like_operand(bill_id)
    if not safe_id:
        return {"paid": False, "error": "invalid_bill_reference"}
    literal = _escape_query_literal(safe_id)
    query = (
        "SELECT Id, DocNumber, TotalAmt, Balance, VendorRef "
        f"FROM Bill WHERE Id = '{literal}'"
    )
    url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                params={"query": query},
                headers={"Authorization": f"Bearer {connection.access_token}"},
                timeout=30,
            )
            if response.status_code == 401:
                return {"paid": False, "error": "token_expired", "needs_reauth": True}

            response.raise_for_status()
            bills = response.json().get("QueryResponse", {}).get("Bill", [])
            if not bills:
                return {"paid": False, "reason": "not_found"}

            bill = bills[0]
            total_amt = float(bill.get("TotalAmt") or 0)
            balance = float(bill.get("Balance") or 0)
            bill_id_val = bill.get("Id") or ""

            if balance <= 0 and total_amt > 0:
                # Fully paid — check if closed by VendorCredit instead of payment
                # Query for BillPayment linked to this bill
                bp_query = (
                    "SELECT Id FROM BillPayment WHERE Id IS NOT NULL "
                    f"STARTPOSITION 1 MAXRESULTS 1"
                )
                closure_method = "payment"
                try:
                    bp_url = f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
                    bp_literal = _escape_query_literal(str(bill_id_val))
                    vc_query = (
                        f"SELECT Id FROM VendorCredit "
                        f"WHERE Id IS NOT NULL "
                        f"STARTPOSITION 1 MAXRESULTS 1"
                    )
                    # Heuristic: if bill is paid (Balance=0) but we can't find a
                    # direct BillPayment reference, check for VendorCredits
                    # For now, mark closure_method based on available data
                    if not bill.get("LinkedTxn"):
                        closure_method = "unknown_non_payment"
                    else:
                        linked = bill.get("LinkedTxn") or []
                        has_payment = any(
                            str(lt.get("TxnType") or "").lower() == "billpayment"
                            for lt in (linked if isinstance(linked, list) else [])
                        )
                        has_credit = any(
                            str(lt.get("TxnType") or "").lower() in ("vendorcredit", "creditcardcredit")
                            for lt in (linked if isinstance(linked, list) else [])
                        )
                        if has_credit and not has_payment:
                            closure_method = "credit_applied"
                        elif has_payment:
                            closure_method = "payment"
                        else:
                            closure_method = "unknown_non_payment"
                except Exception:
                    pass  # Fall through with default closure_method

                result = {
                    "paid": True,
                    "payment_amount": round(total_amt, 2),
                    "payment_date": "",
                    "payment_method": "",
                    "payment_reference": bill_id_val,
                    "partial": False,
                    "remaining_balance": 0.0,
                }
                if closure_method != "payment":
                    result["closure_method"] = closure_method
                return result

            elif balance < total_amt:
                # Partial payment
                paid_amount = round(total_amt - balance, 2)
                return {
                    "paid": False,
                    "payment_amount": paid_amount,
                    "payment_date": "",
                    "payment_method": "",
                    "payment_reference": bill_id_val,
                    "partial": True,
                    "remaining_balance": round(balance, 2),
                }
            else:
                # Check for voided payments (Balance == TotalAmt but voided
                # BillPayments exist in LinkedTxn)
                linked = bill.get("LinkedTxn") or []
                if isinstance(linked, list):
                    has_voided = any(
                        str(lt.get("TxnType") or "").lower() == "billpayment"
                        for lt in linked
                    )
                    if has_voided and balance >= total_amt and total_amt > 0:
                        return {
                            "paid": False,
                            "payment_failed": True,
                            "reason": "payment_voided",
                        }
                return {"paid": False, "reason": "unpaid"}
    except httpx.HTTPStatusError as e:
        logger.error("QuickBooks payment status HTTP error: status=%d", e.response.status_code)
        return {"paid": False, "error": f"http_{e.response.status_code}"}
    except Exception as e:
        logger.error("QuickBooks payment status error: %s", type(e).__name__)
        return {"paid": False, "error": "payment_status_lookup_failed"}


# ==================== Chart of Accounts ====================

_QB_ACCOUNT_TYPE_MAP = {
    "bank": "asset",
    "other current asset": "asset",
    "fixed asset": "asset",
    "other asset": "asset",
    "accounts receivable": "asset",
    "accounts payable": "liability",
    "credit card": "liability",
    "other current liability": "liability",
    "long term liability": "liability",
    "equity": "equity",
    "income": "revenue",
    "other income": "revenue",
    "expense": "expense",
    "other expense": "expense",
    "cost of goods sold": "expense",
}


async def get_chart_of_accounts_quickbooks(connection) -> List[Dict[str, Any]]:
    """Fetch all accounts from QuickBooks Online.

    Returns a normalized list of account dicts.  Returns ``[]`` on any error
    so the caller is never blocked.
    """
    if not connection.access_token or not connection.realm_id:
        return []

    url = (
        f"https://quickbooks.api.intuit.com/v3/company/{connection.realm_id}/query"
    )
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                params={"query": "SELECT * FROM Account MAXRESULTS 1000"},
                headers=_quickbooks_headers(connection),
                timeout=60,
            )

            if response.status_code == 401:
                logger.warning("QuickBooks token expired during chart-of-accounts fetch")
                return []

            response.raise_for_status()
            result = response.json()

            accounts: List[Dict[str, Any]] = []
            for acc in result.get("QueryResponse", {}).get("Account", []):
                raw_type = str(acc.get("AccountType") or "").strip().lower()
                accounts.append({
                    "id": str(acc.get("Id") or ""),
                    "code": str(acc.get("AcctNum") or ""),
                    "name": str(acc.get("Name") or ""),
                    "type": _QB_ACCOUNT_TYPE_MAP.get(raw_type, raw_type),
                    "sub_type": str(acc.get("AccountSubType") or ""),
                    "active": acc.get("Active", True) is True,
                    "currency": str(acc.get("CurrencyRef", {}).get("value", "") if isinstance(acc.get("CurrencyRef"), dict) else ""),
                })
            return accounts

    except Exception as e:
        logger.error("Failed to fetch QuickBooks chart of accounts: %s", type(e).__name__)
        return []
