"""
Xero ERP Integration

All Xero-specific API calls: journal entries, bills, vendors, credits,
settlements, attachments, and token refresh.
"""
from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

import httpx

from clearledgr.integrations.erp_sanitization import (
    _build_xero_vendor_lookup_where,
    _escape_query_literal,
    _sanitize_xero_where_operand,
)

logger = logging.getLogger(__name__)

_ERP_TIMEOUT = 30


def _xero_headers(
    connection,
    *,
    idempotency_key: Optional[str] = None,
) -> Dict[str, str]:
    headers = {
        "Authorization": f"Bearer {connection.access_token}",
        "Content-Type": "application/json",
        "xero-tenant-id": str(connection.tenant_id or ""),
    }
    if idempotency_key:
        headers["Idempotency-Key"] = str(idempotency_key)[:128]
    return headers


def _extract_xero_validation_message(payload: Optional[Dict[str, Any]]) -> Optional[str]:
    if not isinstance(payload, dict):
        return None
    message = str(payload.get("Message") or "").strip()
    if message:
        return message
    for key in ("Allocations", "Payments", "CreditNotes"):
        rows = payload.get(key)
        if not isinstance(rows, list):
            continue
        for row in rows:
            if not isinstance(row, dict):
                continue
            errors = row.get("ValidationErrors")
            if isinstance(errors, list) and errors:
                for err in errors:
                    if isinstance(err, dict):
                        detail = str(err.get("Message") or "").strip()
                        if detail:
                            return detail
    return None


# ==================== Journal Entry ====================

async def post_to_xero(
    connection,
    entry: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Post journal entry to Xero.

    Uses Xero API:
    https://developer.xero.com/documentation/api/accounting/manualjournals
    """
    if not connection.access_token or not connection.tenant_id:
        return {"status": "error", "erp": "xero", "reason": "Xero not properly configured"}

    # Build Xero manual journal format
    xero_journal = {
        "Date": entry.get("date", datetime.now().strftime("%Y-%m-%d")),
        "Narration": entry.get("description", "Auto-generated by Clearledgr"),
        "JournalLines": [],
    }

    for line in entry.get("lines", []):
        xero_line = {
            "LineAmount": line.get("debit", 0) if line.get("debit", 0) > 0 else -line.get("credit", 0),
            "AccountCode": line.get("account", "200"),  # Xero uses account codes
            "Description": line.get("account_name", ""),
        }
        xero_journal["JournalLines"].append(xero_line)

    # Make API call
    url = "https://api.xero.com/api.xro/2.0/ManualJournals"

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.post(
                url,
                json={"ManualJournals": [xero_journal]},
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "Content-Type": "application/json",
                    "xero-tenant-id": connection.tenant_id,
                },
                timeout=30,
            )

            if response.status_code == 401:
                logger.warning("Xero token expired, needs refresh")
                return {"status": "error", "erp": "xero", "reason": "Token expired", "needs_reauth": True}

            response.raise_for_status()
            result = response.json()

            journals = result.get("ManualJournals", [])
            if journals:
                journal_id = journals[0].get("ManualJournalID")
                logger.info(f"Posted to Xero: {journal_id}")
                return {
                    "status": "success",
                    "erp": "xero",
                    "entry_id": journal_id,
                }

            return {"status": "error", "erp": "xero", "reason": "No journal returned"}

    except httpx.HTTPStatusError as e:
        logger.error("Xero API error: %s", e.response.status_code)
        return {"status": "error", "erp": "xero", "reason": f"Xero API {e.response.status_code}"}
    except Exception as e:
        logger.error("Xero error: %s", type(e).__name__)
        return {"status": "error", "erp": "xero", "reason": "posting_failed"}


# ==================== Token Refresh ====================

async def refresh_xero_token(connection) -> Optional[str]:
    """Refresh Xero OAuth token."""
    if not connection.refresh_token or not connection.client_id or not connection.client_secret:
        return None

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.post(
                "https://identity.xero.com/connect/token",
                data={
                    "grant_type": "refresh_token",
                    "refresh_token": connection.refresh_token,
                },
                auth=(connection.client_id, connection.client_secret),
            )
            response.raise_for_status()
            tokens = response.json()

            connection.access_token = tokens.get("access_token")
            connection.refresh_token = tokens.get("refresh_token")

            return connection.access_token
    except Exception as e:
        logger.error("Failed to refresh Xero token: %s", type(e).__name__)
        return None


# ==================== Bill Posting ====================

async def post_bill_to_xero(
    connection,
    bill,
    gl_map: Optional[Dict[str, str]] = None,
) -> Dict[str, Any]:
    """
    Post vendor bill to Xero.

    API: https://developer.xero.com/documentation/api/accounting/invoices
    Type: ACCPAY (Accounts Payable / Bill)
    """
    from clearledgr.integrations.erp_router import get_account_code

    if not connection.access_token or not connection.tenant_id:
        return {"status": "error", "erp": "xero", "reason": "Xero not properly configured"}

    expense_account = get_account_code("xero", "expenses", gl_map)

    # Build Xero Invoice (ACCPAY type = Bill)
    xero_bill = {
        "Type": "ACCPAY",  # Accounts Payable = Bill
        "Contact": {"ContactID": bill.vendor_id, "Name": bill.vendor_name},
        "Date": bill.invoice_date or datetime.now().strftime("%Y-%m-%d"),
        "DueDate": bill.due_date,
        "InvoiceNumber": bill.invoice_number,
        "Reference": bill.po_number,
        "Status": "AUTHORISED",  # Ready for payment
        "LineItems": [],
    }

    # Add line items
    if bill.line_items:
        for item in bill.line_items:
            xero_bill["LineItems"].append({
                "Description": item.get("description", ""),
                "Quantity": item.get("quantity", 1),
                "UnitAmount": item.get("unit_amount", item.get("amount", 0)),
                "AccountCode": item.get("account_code", expense_account),
                "TaxType": item.get("tax_type", "NONE"),
            })
    else:
        xero_bill["LineItems"].append({
            "Description": bill.description or f"Invoice {bill.invoice_number}",
            "Quantity": 1,
            "UnitAmount": bill.amount,
            "AccountCode": expense_account,
            "TaxType": "NONE",
        })

    # Apply tax to line items if tax_amount provided
    if getattr(bill, "tax_amount", None) and bill.tax_amount > 0:
        for li in xero_bill["LineItems"]:
            li["TaxType"] = "OUTPUT"  # Standard tax
        xero_bill["TotalTax"] = bill.tax_amount

    # Apply discount as negative line
    if getattr(bill, "discount_amount", None) and bill.discount_amount > 0:
        xero_bill["LineItems"].append({
            "Description": f"Discount ({bill.discount_terms or 'early payment'})",
            "Quantity": 1,
            "UnitAmount": -bill.discount_amount,
            "AccountCode": expense_account,
            "TaxType": "NONE",
        })

    url = "https://api.xero.com/api.xro/2.0/Invoices"

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.post(
                url,
                json={"Invoices": [xero_bill]},
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "Content-Type": "application/json",
                    "xero-tenant-id": connection.tenant_id,
                },
                timeout=30,
            )

            if response.status_code == 401:
                return {"status": "error", "erp": "xero", "reason": "Token expired", "needs_reauth": True}

            response.raise_for_status()
            result = response.json()

            invoices = result.get("Invoices", [])
            if invoices:
                inv = invoices[0]
                logger.info("Posted Bill to Xero: %s", inv.get("InvoiceID"))
                return {
                    "status": "success",
                    "erp": "xero",
                    "bill_id": inv.get("InvoiceID"),
                    "invoice_number": inv.get("InvoiceNumber"),
                }

            return {"status": "error", "erp": "xero", "reason": "no_invoice_returned"}

    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("Xero Bill API HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        if status_code == 404:
            reason = "erp_configuration_stale"
            logger.error(
                "Xero 404 — likely tenant_id mismatch (tenant_id=%s). "
                "Verify the organisation is accessible with current credentials.",
                connection.tenant_id,
            )
        return {
            "status": "error",
            "erp": "xero",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("Xero Bill error: %s", type(e).__name__)
        return {"status": "error", "erp": "xero", "reason": "bill_posting_failed"}


# ==================== Credit Note Lookup & Application ====================

async def find_credit_note_xero(
    connection,
    credit_note_number: str,
) -> Optional[Dict[str, Any]]:
    """Find an AP credit note in Xero by document number."""
    if not connection.access_token or not connection.tenant_id:
        return None
    safe_number = _sanitize_xero_where_operand(credit_note_number)
    if not safe_number:
        return None
    literal = _escape_query_literal(safe_number)
    where_clause = f'Type=="ACCPAYCREDIT" AND CreditNoteNumber=="{literal}"'
    url = "https://api.xero.com/api.xro/2.0/CreditNotes"
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                params={"where": where_clause},
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "xero-tenant-id": connection.tenant_id,
                },
                timeout=30,
            )
            response.raise_for_status()
            credit_notes = response.json().get("CreditNotes", [])
            if credit_notes:
                note = credit_notes[0]
                return {
                    "credit_note_id": note.get("CreditNoteID"),
                    "credit_note_number": note.get("CreditNoteNumber"),
                    "remaining_credit": note.get("RemainingCredit"),
                    "status": note.get("Status"),
                    "currency": note.get("CurrencyCode"),
                    "erp": "xero",
                }
    except Exception as e:
        logger.error("Xero credit note lookup error: %s", e)
    return None


async def apply_credit_note_to_xero(
    connection,
    application,
    *,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Allocate an existing Xero AP credit note against a posted bill."""
    if not connection.access_token or not connection.tenant_id:
        return {"status": "error", "erp": "xero", "reason": "Xero not properly configured"}

    missing_fields = []
    if not str(application.target_erp_reference or "").strip():
        missing_fields.append("target_erp_reference")
    if not str(application.credit_note_number or "").strip():
        missing_fields.append("credit_note_number")
    if float(application.amount or 0.0) <= 0:
        missing_fields.append("amount")
    if missing_fields:
        return {
            "status": "error",
            "erp": "xero",
            "reason": "xero_credit_application_validation_failed",
            "missing_fields": missing_fields,
        }

    credit_note = await find_credit_note_xero(connection, str(application.credit_note_number or ""))
    if not credit_note or not credit_note.get("credit_note_id"):
        return {
            "status": "error",
            "erp": "xero",
            "reason": "credit_note_not_found",
            "credit_note_number": application.credit_note_number,
        }

    remaining_credit = credit_note.get("remaining_credit")
    try:
        if remaining_credit is not None and round(float(application.amount or 0.0), 2) > round(float(remaining_credit), 2):
            return {
                "status": "error",
                "erp": "xero",
                "reason": "credit_amount_exceeds_remaining_credit",
                "credit_note_number": application.credit_note_number,
                "remaining_credit": round(float(remaining_credit), 2),
            }
    except (TypeError, ValueError):
        pass

    allocation_request = {
        "Allocations": [
            {
                "Invoice": {"InvoiceID": str(application.target_erp_reference).strip()},
                "Amount": round(float(application.amount or 0.0), 2),
                "Date": datetime.now().strftime("%Y-%m-%d"),
            }
        ]
    }
    url = f"https://api.xero.com/api.xro/2.0/CreditNotes/{credit_note['credit_note_id']}/Allocations"

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.put(
                url,
                params={"summarizeErrors": "true"},
                json=allocation_request,
                headers=_xero_headers(connection, idempotency_key=idempotency_key),
                timeout=30,
            )
            if response.status_code == 401:
                return {"status": "error", "erp": "xero", "reason": "Token expired", "needs_reauth": True}

            response.raise_for_status()
            payload = response.json()
            validation_message = _extract_xero_validation_message(payload)
            if validation_message:
                return {
                    "status": "error",
                    "erp": "xero",
                    "reason": validation_message,
                    "credit_note_number": application.credit_note_number,
                }

            allocations = payload.get("Allocations", [])
            if allocations:
                allocation = allocations[0]
                application_reference = (
                    allocation.get("AllocationID")
                    or f"{credit_note['credit_note_id']}:{str(application.target_erp_reference).strip()}"
                )
                return {
                    "status": "success",
                    "erp": "xero",
                    "erp_reference": application_reference,
                    "target_erp_reference": str(application.target_erp_reference).strip(),
                    "credit_note_reference": credit_note.get("credit_note_id"),
                    "credit_note_number": credit_note.get("credit_note_number"),
                    "amount": allocation.get("Amount"),
                }

            return {"status": "error", "erp": "xero", "reason": "no_allocation_returned"}
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("Xero credit allocation HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        validation_message = _extract_xero_validation_message(payload)
        if validation_message:
            reason = validation_message
        return {
            "status": "error",
            "erp": "xero",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("Xero credit allocation error: %s", type(e).__name__)
        return {"status": "error", "erp": "xero", "reason": "credit_application_failed"}


# ==================== Settlement ====================

async def apply_settlement_to_xero(
    connection,
    application,
    *,
    gl_map: Optional[Dict[str, str]] = None,
    idempotency_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Create a Xero bill payment against a posted payable invoice."""
    from clearledgr.integrations.erp_router import get_account_code

    if not connection.access_token or not connection.tenant_id:
        return {"status": "error", "erp": "xero", "reason": "Xero not properly configured"}

    source_document_type = str(application.source_document_type or "").strip().lower()
    if source_document_type == "refund":
        return {
            "status": "error",
            "erp": "xero",
            "reason": "refund_settlement_api_not_available_for_connector",
        }

    missing_fields = []
    if not str(application.target_erp_reference or "").strip():
        missing_fields.append("target_erp_reference")
    if float(application.amount or 0.0) <= 0:
        missing_fields.append("amount")
    if missing_fields:
        return {
            "status": "error",
            "erp": "xero",
            "reason": "xero_settlement_validation_failed",
            "missing_fields": missing_fields,
        }

    payment_request = {
        "Payments": [
            {
                "Invoice": {"InvoiceID": str(application.target_erp_reference).strip()},
                "Account": {"Code": get_account_code("xero", "cash", gl_map)},
                "Date": datetime.now().strftime("%Y-%m-%d"),
                "Amount": round(float(application.amount or 0.0), 2),
            }
        ]
    }
    payment = payment_request["Payments"][0]
    if application.source_reference:
        payment["Reference"] = str(application.source_reference).strip()[:255]

    url = "https://api.xero.com/api.xro/2.0/Payments"
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.put(
                url,
                params={"summarizeErrors": "true"},
                json=payment_request,
                headers=_xero_headers(connection, idempotency_key=idempotency_key),
                timeout=30,
            )
            if response.status_code == 401:
                return {"status": "error", "erp": "xero", "reason": "Token expired", "needs_reauth": True}

            response.raise_for_status()
            payload = response.json()
            validation_message = _extract_xero_validation_message(payload)
            if validation_message:
                return {
                    "status": "error",
                    "erp": "xero",
                    "reason": validation_message,
                    "source_reference": application.source_reference,
                }

            payments = payload.get("Payments", [])
            if payments:
                payment_result = payments[0]
                return {
                    "status": "success",
                    "erp": "xero",
                    "erp_reference": payment_result.get("PaymentID"),
                    "payment_id": payment_result.get("PaymentID"),
                    "target_erp_reference": str(application.target_erp_reference).strip(),
                    "amount": payment_result.get("Amount"),
                    "source_reference": payment_result.get("Reference") or application.source_reference,
                }

            return {"status": "error", "erp": "xero", "reason": "no_payment_returned"}
    except httpx.HTTPStatusError as e:
        status_code = e.response.status_code
        logger.error("Xero settlement payment HTTP error: status=%d", status_code)
        reason = f"http_{status_code}"
        try:
            payload = e.response.json()
        except Exception:
            payload = None
        validation_message = _extract_xero_validation_message(payload)
        if validation_message:
            reason = validation_message
        return {
            "status": "error",
            "erp": "xero",
            "reason": reason,
            "needs_reauth": status_code == 401,
        }
    except Exception as e:
        logger.error("Xero settlement payment error: %s", type(e).__name__)
        return {"status": "error", "erp": "xero", "reason": "settlement_application_failed"}


# ==================== Vendor Management ====================

async def create_vendor_xero(
    connection,
    vendor,
) -> Dict[str, Any]:
    """Create vendor (Contact) in Xero."""
    if not connection.access_token or not connection.tenant_id:
        return {"status": "error", "erp": "xero", "reason": "Xero not configured"}

    xero_contact = {
        "Name": vendor.name,
        "IsSupplier": True,
        "ContactStatus": "ACTIVE",
    }

    if vendor.email:
        xero_contact["EmailAddress"] = vendor.email
    if vendor.phone:
        xero_contact["Phones"] = [{"PhoneType": "DEFAULT", "PhoneNumber": vendor.phone}]
    if vendor.tax_id:
        xero_contact["TaxNumber"] = vendor.tax_id
    if vendor.payment_terms:
        # Map to Xero payment terms
        days = int(''.join(filter(str.isdigit, vendor.payment_terms)) or "30")
        xero_contact["PaymentTerms"] = {"Bills": {"Day": days, "Type": "DAYSAFTERBILLDATE"}}

    url = "https://api.xero.com/api.xro/2.0/Contacts"

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.post(
                url,
                json={"Contacts": [xero_contact]},
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "Content-Type": "application/json",
                    "xero-tenant-id": connection.tenant_id,
                },
                timeout=30,
            )
            response.raise_for_status()
            result = response.json()

            contacts = result.get("Contacts", [])
            if contacts:
                c = contacts[0]
                return {
                    "status": "success",
                    "vendor_id": c.get("ContactID"),
                    "name": c.get("Name"),
                }
            return {"status": "error", "erp": "xero", "reason": "No contact returned"}
    except Exception as e:
        logger.error("Xero vendor creation error: %s", type(e).__name__)
        return {"status": "error", "erp": "xero", "reason": "vendor_creation_failed"}


async def find_vendor_xero(
    connection,
    name: Optional[str] = None,
    email: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Find vendor in Xero."""
    if not connection.access_token or not connection.tenant_id:
        return None

    url = "https://api.xero.com/api.xro/2.0/Contacts"
    name_operand = _sanitize_xero_where_operand(name)
    params = {"where": _build_xero_vendor_lookup_where(name_operand=name_operand)}

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                params=params,
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "xero-tenant-id": connection.tenant_id,
                },
                timeout=30,
            )
            response.raise_for_status()
            result = response.json()

            contacts = result.get("Contacts", [])
            for c in contacts:
                if email and c.get("EmailAddress") != email:
                    continue
                return {
                    "vendor_id": c.get("ContactID"),
                    "name": c.get("Name"),
                    "email": c.get("EmailAddress"),
                }
    except Exception as e:
        logger.error(f"Xero vendor search error: {e}")

    return None


# ==================== Bill Finder ====================

async def find_bill_xero(
    connection,
    invoice_number: str,
) -> Optional[Dict[str, Any]]:
    """Check if a bill (accounts payable invoice) already exists in Xero."""
    if not connection.access_token or not connection.tenant_id:
        return None
    safe_number = _sanitize_xero_where_operand(invoice_number)
    if not safe_number:
        return None
    literal = _escape_query_literal(safe_number)
    where_clause = f'Type=="ACCPAY" AND InvoiceNumber=="{literal}"'
    url = "https://api.xero.com/api.xro/2.0/Invoices"
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                params={"where": where_clause},
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "xero-tenant-id": connection.tenant_id,
                },
                timeout=30,
            )
            response.raise_for_status()
            invoices = response.json().get("Invoices", [])
            if invoices:
                inv = invoices[0]
                return {
                    "bill_id": inv.get("InvoiceID"),
                    "doc_number": inv.get("InvoiceNumber"),
                    "amount": inv.get("Total"),
                    "erp": "xero",
                }
    except Exception as e:
        logger.error("Xero bill lookup error: %s", e)
    return None


# ==================== Attachment ====================

async def _attach_to_xero(
    connection, bill_id: str, file_bytes: bytes, filename: str,
) -> Optional[Dict[str, Any]]:
    """Upload attachment to a Xero ACCPAY Invoice."""
    creds = connection.credentials or {}
    access_token = creds.get("access_token", "")
    tenant_id = creds.get("tenant_id", "")
    if not access_token or not tenant_id:
        return None
    safe_name = _sanitize_xero_where_operand(filename) or "invoice.pdf"
    url = f"https://api.xero.com/api.xro/2.0/Invoices/{bill_id}/Attachments/{safe_name}"
    headers = {
        "Authorization": f"Bearer {access_token}",
        "xero-tenant-id": tenant_id,
        "Content-Type": "application/pdf",
    }
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.put(url, headers=headers, content=file_bytes)
        resp.raise_for_status()
    return {"attached": True, "erp": "xero"}


# ==================== Payment Status Lookup ====================

async def get_payment_status_xero(
    connection,
    bill_id: str,
) -> Dict[str, Any]:
    """Read payment status for a Xero ACCPAY invoice. GET only — never executes payments.

    Checks the invoice Status (PAID) or AmountDue == 0 for full payment.
    AmountDue > 0 but < Total means partial payment.
    """
    if not connection.access_token or not connection.tenant_id:
        return {"paid": False, "error": "Xero not properly configured"}

    url = f"https://api.xero.com/api.xro/2.0/Invoices/{bill_id}"
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "xero-tenant-id": str(connection.tenant_id or ""),
                },
                timeout=30,
            )
            if response.status_code == 401:
                return {"paid": False, "error": "token_expired", "needs_reauth": True}

            response.raise_for_status()
            invoices = response.json().get("Invoices", [])
            if not invoices:
                return {"paid": False, "reason": "not_found"}

            invoice = invoices[0]
            status = str(invoice.get("Status") or "").upper()
            total = float(invoice.get("Total") or 0)
            amount_due = float(invoice.get("AmountDue") or 0)
            amount_paid = float(invoice.get("AmountPaid") or 0)

            # Extract payment details from Payments array if available
            payments = invoice.get("Payments") or []
            payment_date = ""
            payment_reference = ""
            has_voided_payment = False
            if isinstance(payments, list) and payments:
                last_payment = payments[-1]
                if isinstance(last_payment, dict):
                    payment_date = str(last_payment.get("Date") or "").strip()
                    payment_reference = str(last_payment.get("PaymentID") or "").strip()
                # Check for DELETED or VOIDED payments
                for pmt in payments:
                    if isinstance(pmt, dict):
                        pmt_status = str(pmt.get("Status") or "").upper()
                        if pmt_status in ("DELETED", "VOIDED"):
                            has_voided_payment = True

            # Check for credit note applications
            credit_notes = invoice.get("CreditNotes") or []
            has_credits = isinstance(credit_notes, list) and len(credit_notes) > 0

            if status == "PAID" or (amount_due <= 0 and total > 0):
                # Determine closure method
                closure_method = "payment"
                if has_credits and not payment_reference:
                    closure_method = "credit_applied"
                elif not payment_reference and not has_credits:
                    closure_method = "unknown_non_payment"

                result = {
                    "paid": True,
                    "payment_amount": round(amount_paid or total, 2),
                    "payment_date": payment_date,
                    "payment_method": "",
                    "payment_reference": payment_reference,
                    "partial": False,
                    "remaining_balance": 0.0,
                }
                if closure_method != "payment":
                    result["closure_method"] = closure_method
                return result
            elif amount_paid > 0 and amount_due > 0:
                return {
                    "paid": False,
                    "payment_amount": round(amount_paid, 2),
                    "payment_date": payment_date,
                    "payment_method": "",
                    "payment_reference": payment_reference,
                    "partial": True,
                    "remaining_balance": round(amount_due, 2),
                }
            else:
                # Check for voided/deleted payments indicating a failed payment
                if has_voided_payment:
                    return {
                        "paid": False,
                        "payment_failed": True,
                        "reason": "payment_voided_or_deleted",
                    }
                return {"paid": False, "reason": "unpaid"}
    except httpx.HTTPStatusError as e:
        logger.error("Xero payment status HTTP error: status=%d", e.response.status_code)
        return {"paid": False, "error": f"http_{e.response.status_code}"}
    except Exception as e:
        logger.error("Xero payment status error: %s", type(e).__name__)
        return {"paid": False, "error": "payment_status_lookup_failed"}


# ==================== Chart of Accounts ====================

_XERO_ACCOUNT_TYPE_MAP = {
    "bank": "asset",
    "current": "asset",
    "currliab": "liability",
    "depreciatn": "expense",
    "directcosts": "expense",
    "equity": "equity",
    "expense": "expense",
    "fixed": "asset",
    "inventory": "asset",
    "liability": "liability",
    "noncurrent": "asset",
    "otherincome": "revenue",
    "overheads": "expense",
    "prepayment": "asset",
    "revenue": "revenue",
    "sales": "revenue",
    "termliab": "liability",
    "paygliability": "liability",
    "superannuationexpense": "expense",
    "superannuationliability": "liability",
    "wagesexpense": "expense",
}


async def get_chart_of_accounts_xero(connection) -> List[Dict[str, Any]]:
    """Fetch all accounts from Xero.

    Returns a normalized list of account dicts.  Returns ``[]`` on any error
    so the caller is never blocked.
    """
    if not connection.access_token or not connection.tenant_id:
        return []

    url = "https://api.xero.com/api.xro/2.0/Accounts"
    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            response = await client.get(
                url,
                headers={
                    "Authorization": f"Bearer {connection.access_token}",
                    "xero-tenant-id": str(connection.tenant_id or ""),
                },
                timeout=60,
            )

            if response.status_code == 401:
                logger.warning("Xero token expired during chart-of-accounts fetch")
                return []

            response.raise_for_status()
            result = response.json()

            accounts: List[Dict[str, Any]] = []
            for acc in result.get("Accounts", []):
                raw_type = str(acc.get("Type") or "").strip().lower()
                accounts.append({
                    "id": str(acc.get("AccountID") or ""),
                    "code": str(acc.get("Code") or ""),
                    "name": str(acc.get("Name") or ""),
                    "type": _XERO_ACCOUNT_TYPE_MAP.get(raw_type, raw_type),
                    "sub_type": str(acc.get("Class") or ""),
                    "active": str(acc.get("Status") or "").upper() == "ACTIVE",
                    "currency": str(acc.get("CurrencyCode") or ""),
                })
            return accounts

    except Exception as e:
        logger.error("Failed to fetch Xero chart of accounts: %s", type(e).__name__)
        return []


# ==================== Vendor List ====================


async def list_all_vendors_xero(connection) -> List[Dict[str, Any]]:
    """Fetch all supplier contacts from Xero with pagination.

    Xero Contacts API uses ``page`` (1-indexed, 100 per page).
    Filters to ``IsSupplier==true`` to get vendors only.
    Returns a normalized list of vendor dicts.  Returns ``[]`` on any error.
    """
    if not connection.access_token or not connection.tenant_id:
        return []

    url = "https://api.xero.com/api.xro/2.0/Contacts"
    headers = {
        "Authorization": f"Bearer {connection.access_token}",
        "xero-tenant-id": str(connection.tenant_id or ""),
    }
    page = 1
    all_vendors: List[Dict[str, Any]] = []

    try:
        async with httpx.AsyncClient(timeout=_ERP_TIMEOUT) as client:
            while True:
                response = await client.get(
                    url,
                    params={
                        "where": "IsSupplier==true",
                        "page": page,
                    },
                    headers=headers,
                    timeout=60,
                )

                if response.status_code == 401:
                    logger.warning("Xero token expired during vendor list fetch")
                    break

                response.raise_for_status()
                result = response.json()

                contacts = result.get("Contacts", [])
                if not contacts:
                    break

                for c in contacts:
                    addrs = c.get("Addresses") or []
                    addr_parts = []
                    for a in addrs:
                        if a.get("AddressType") == "POBOX" or a.get("AddressType") == "STREET":
                            addr_parts = list(filter(None, [
                                a.get("AddressLine1"), a.get("City"),
                                a.get("Region"), a.get("PostalCode"),
                                a.get("Country"),
                            ]))
                            break

                    phones = c.get("Phones") or []
                    phone = ""
                    for p in phones:
                        if p.get("PhoneNumber"):
                            phone = str(p["PhoneNumber"])
                            break

                    all_vendors.append({
                        "vendor_id": str(c.get("ContactID") or ""),
                        "name": str(c.get("Name") or ""),
                        "email": str(c.get("EmailAddress") or ""),
                        "phone": phone,
                        "tax_id": str(c.get("TaxNumber") or ""),
                        "currency": str(c.get("DefaultCurrency") or ""),
                        "active": str(c.get("ContactStatus") or "").upper() == "ACTIVE",
                        "address": ", ".join(addr_parts),
                        "payment_terms": "",
                        "balance": float(c.get("Balances", {}).get("AccountsPayable", {}).get("Outstanding") or 0),
                    })

                if len(contacts) < 100:
                    break
                page += 1

        return all_vendors

    except Exception as e:
        logger.error("Failed to fetch Xero vendor list: %s", type(e).__name__)
        return all_vendors or []
