#!/bin/bash
#
# Clearledgr Gmail Extension Build Script
#
# Usage:
#   ./build.sh dev      # Development build (127.0.0.1 API)
#   ./build.sh staging  # Staging build (staging.clearledgr.com)
#   ./build.sh prod     # Production build (api.clearledgr.com)
#   ./build.sh pack     # Create signed CRX for enterprise deployment
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/build"
ENV="${1:-dev}"

cd "$SCRIPT_DIR"

echo "========================================"
echo "Clearledgr Gmail Extension Build"
echo "Environment: $ENV"
echo "========================================"

# Clean previous build
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

# Build InboxSDK layer with webpack (bundles ES modules)
echo "Building InboxSDK layer with webpack..."
npm run build --silent

# Copy extension files (InboxSDK-only implementation)
echo "Copying extension files..."
cp -r "$SCRIPT_DIR/icons" "$BUILD_DIR/"
cp -r "$SCRIPT_DIR/vendor" "$BUILD_DIR/" 2>/dev/null || true
cp "$SCRIPT_DIR/manifest.json" "$BUILD_DIR/"
cp "$SCRIPT_DIR/background.js" "$BUILD_DIR/"
cp "$SCRIPT_DIR/options.html" "$BUILD_DIR/" 2>/dev/null || true
cp "$SCRIPT_DIR/options.js" "$BUILD_DIR/" 2>/dev/null || true

# Content scripts (required by manifest)
cp "$SCRIPT_DIR/queue-manager.js" "$BUILD_DIR/"
cp "$SCRIPT_DIR/content-script.js" "$BUILD_DIR/"

# InboxSDK bundle output (required by manifest: dist/inboxsdk-layer.js + dist/pageWorld.js)
mkdir -p "$BUILD_DIR/dist"
cp "$SCRIPT_DIR/dist/inboxsdk-layer.js" "$BUILD_DIR/dist/"
cp "$SCRIPT_DIR/dist/inboxsdk-layer.js.map" "$BUILD_DIR/dist/" 2>/dev/null || true
cp "$SCRIPT_DIR/dist/pageWorld.js" "$BUILD_DIR/dist/"
cp "$SCRIPT_DIR/dist/pageWorld.js.map" "$BUILD_DIR/dist/" 2>/dev/null || true

# Configure API endpoint based on environment
echo "Configuring for $ENV environment..."

case $ENV in
  dev)
    API_URL="http://127.0.0.1:8000"
    ;;
  staging)
    API_URL="https://staging-api.clearledgr.com"
    ;;
  prod)
    API_URL="https://api.clearledgr.com"
    ;;
  pack)
    API_URL="https://api.clearledgr.com"
    ;;
  *)
    echo "Unknown environment: $ENV"
    echo "Usage: ./build.sh [dev|staging|prod|pack]"
    exit 1
    ;;
esac

# Create config.js with environment settings
cat > "$BUILD_DIR/config.js" << EOF
// Auto-generated by build.sh - DO NOT EDIT
const CLEARLEDGR_CONFIG = {
  API_URL: '$API_URL',
  ENV: '$ENV',
  VERSION: '$(grep '"version"' "$SCRIPT_DIR/manifest.json" | cut -d'"' -f4)',
  BUILD_TIME: '$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
};

// Make available globally
if (typeof window !== 'undefined') {
  window.CLEARLEDGR_CONFIG = CLEARLEDGR_CONFIG;
}
if (typeof self !== 'undefined') {
  self.CLEARLEDGR_CONFIG = CLEARLEDGR_CONFIG;
}
EOF

# Update manifest for production
if [ "$ENV" = "prod" ] || [ "$ENV" = "pack" ]; then
  echo "Updating manifest for production..."
  
  # Remove localhost from host_permissions
  if command -v jq &> /dev/null; then
    jq '.host_permissions = [.host_permissions[] | select(startswith("http://localhost") | not)]' \
      "$BUILD_DIR/manifest.json" > "$BUILD_DIR/manifest.tmp"
    mv "$BUILD_DIR/manifest.tmp" "$BUILD_DIR/manifest.json"
  else
    echo "Warning: jq not installed, skipping manifest host_permissions cleanup"
  fi
fi

# Add config.js to background service worker
echo "Injecting config into background.js..."
sed -i.bak '1s/^/importScripts("config.js");\n/' "$BUILD_DIR/background.js" 2>/dev/null || \
  sed -i '' '1s/^/importScripts("config.js");\n/' "$BUILD_DIR/background.js"
rm -f "$BUILD_DIR/background.js.bak"

# Create ZIP for Chrome Web Store
echo "Creating ZIP package..."
cd "$BUILD_DIR"
zip -r "../clearledgr-extension-$ENV.zip" . -x "*.DS_Store" -x "__MACOSX/*"
cd "$SCRIPT_DIR"

echo ""
echo "Build complete!"
echo "  ZIP: $SCRIPT_DIR/clearledgr-extension-$ENV.zip"
echo ""

# Create signed CRX for enterprise deployment
if [ "$ENV" = "pack" ]; then
  echo "Creating signed CRX for enterprise deployment..."
  
  KEY_FILE="$SCRIPT_DIR/clearledgr.pem"
  
  if [ ! -f "$KEY_FILE" ]; then
    echo "Generating new signing key..."
    openssl genrsa -out "$KEY_FILE" 2048
    echo "Key saved to: $KEY_FILE"
    echo ""
    echo "IMPORTANT: Keep this key secure! You need it for all future updates."
    echo "           The extension ID is derived from this key."
  fi
  
  # Check if Chrome is available for packing
  if command -v google-chrome &> /dev/null; then
    CHROME="google-chrome"
  elif command -v "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" &> /dev/null; then
    CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  else
    echo "Chrome not found. To create CRX, run:"
    echo "  chrome --pack-extension=$BUILD_DIR --pack-extension-key=$KEY_FILE"
    exit 0
  fi
  
  echo "Packing extension with Chrome..."
  "$CHROME" --pack-extension="$BUILD_DIR" --pack-extension-key="$KEY_FILE"
  
  if [ -f "$BUILD_DIR.crx" ]; then
    mv "$BUILD_DIR.crx" "$SCRIPT_DIR/clearledgr-extension.crx"
    echo ""
    echo "CRX created: $SCRIPT_DIR/clearledgr-extension.crx"
    echo ""
    echo "For enterprise deployment, host the CRX and configure:"
    echo "  ExtensionInstallForcelist or ExtensionInstallAllowlist"
  fi
fi

echo ""
echo "Next steps:"
if [ "$ENV" = "prod" ]; then
  echo "  1. Go to https://chrome.google.com/webstore/devconsole"
  echo "  2. Upload clearledgr-extension-prod.zip"
  echo "  3. Fill in store listing details"
  echo "  4. Submit for review"
elif [ "$ENV" = "pack" ]; then
  echo "  For enterprise deployment:"
  echo "  1. Host clearledgr-extension.crx on your server"
  echo "  2. Get the extension ID from chrome://extensions"
  echo "  3. Configure Chrome policy: ExtensionInstallForcelist"
else
  echo "  1. Go to chrome://extensions"
  echo "  2. Enable Developer Mode"
echo "  3. Click 'Load unpacked' and select: $BUILD_DIR"
fi
